import React from "react";
import { SummaryRead } from "@/lib/types";

export function SummaryPanel({ summary }: { summary: SummaryRead | null }) {
  if (!summary) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center p-8">
        <h3 className="text-[16px] font-medium text-[var(--color-gray-900)] mb-2">No summary available</h3>
        <p className="text-[14px] text-[var(--color-gray-500)] max-w-sm">
          Summary generation is still processing or was not requested for this meeting.
        </p>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-3xl">
      <div className="mb-10">
        <h2 className="text-[18px] font-medium text-[var(--color-gray-900)] mb-4">Overview</h2>
        <p className="text-[14px] leading-relaxed text-[var(--color-gray-700)]">
          {summary.overview}
        </p>
      </div>

      <div className="mb-10 flex gap-2 flex-wrap">
        {summary.keywords.map((kw, i) => (
          <span 
            key={i} 
            className="px-3 py-1 bg-[var(--color-blue-50)] text-[var(--color-blue-700)] text-[14px] font-medium rounded border border-[var(--color-blue-200)]"
          >
            {kw}
          </span>
        ))}
      </div>

      <div className="space-y-8">
        {summary.bullet_notes.map((section, i) => (
          <div key={i}>
            <h3 className="text-[16px] font-medium text-[var(--color-gray-900)] mb-3">{section.title}</h3>
            <ul className="list-disc pl-5 space-y-2">
              {section.points.map((point, j) => (
                <li key={j} className="text-[14px] text-[var(--color-gray-700)] leading-relaxed">
                  {point}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      
      <div className="mt-12 text-[12px] text-[var(--color-gray-400)]">
        Generated by {summary.generated_by}
      </div>
    </div>
  );
}
